### ISSUE TITLE
About Camera Geometry

### ISSUE THREAD

**Issue by iwan21p** [dluvizon/vehicle-dsm#15]
Can you please add the information about the camera geometry (eg: camera spesification, camera positioning, angle of view, angle of camera). I think it is important to know, related to the vehicle speed measurements. I hope you can explain it, thanks.

**Comment by dluvizon** [comment]
Hi @iwan21p ,
The camera is from the Raspberry v2 kit and was installed over the road at 5.5 meters.
Since or method does not require a full calibration setup, we didn't measured the exact angle with respect to the vertical. The intrinsics parameters we can find here: https://www.raspberrypi.org/documentation/hardware/camera/
